### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by catpreneur** [docker-taiga/back#11]
```
taiga-back | Waiting for database to become ready...
taiga-back | trying to connect: host='db' dbname='taiga' user='postgres' password='password'...
taiga-back | Running database update...
taiga-back | Traceback (most recent call last):
taiga-back |   File "manage.py", line 29, in <module>
taiga-back |     execute_from_command_line(sys.argv)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
taiga-back |     utility.execute()
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
taiga-back |     settings.INSTALLED_APPS
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
taiga-back |     self._setup(name)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
taiga-back |     self._wrapped = Settings(settings_module)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
taiga-back |     mod = importlib.import_module(self.SETTINGS_MODULE)
taiga-back |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
taiga-back |     return _bootstrap._gcd_import(name[level:], package, level)
taiga-back |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
taiga-back |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
taiga-back |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
taiga-back |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
taiga-back |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
taiga-back |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | Traceback (most recent call last):
taiga-back |   File "manage.py", line 29, in <module>
taiga-back |     execute_from_command_line(sys.argv)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
taiga-back |     utility.execute()
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
taiga-back |     settings.INSTALLED_APPS
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
taiga-back |     self._setup(name)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
taiga-back |     self._wrapped = Settings(settings_module)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
taiga-back |     mod = importlib.import_module(self.SETTINGS_MODULE)
taiga-back |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
taiga-back |     return _bootstrap._gcd_import(name[level:], package, level)
taiga-back |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
taiga-back |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
taiga-back |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
taiga-back |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
taiga-back |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
taiga-back |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | Traceback (most recent call last):
taiga-back |   File "manage.py", line 29, in <module>
taiga-back |     execute_from_command_line(sys.argv)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
taiga-back |     utility.execute()
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
taiga-back |     settings.INSTALLED_APPS
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
taiga-back |     self._setup(name)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
taiga-back |     self._wrapped = Settings(settings_module)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
taiga-back |     mod = importlib.import_module(self.SETTINGS_MODULE)
taiga-back |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
taiga-back |     return _bootstrap._gcd_import(name[level:], package, level)
taiga-back |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
taiga-back |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
taiga-back |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
taiga-back |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
taiga-back |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
taiga-back |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | Installing cron jobs...
taiga-back | [2020-05-03 02:50:13 +0000] [15] [INFO] Starting gunicorn 19.9.0
taiga-back | [2020-05-03 02:50:13 +0000] [15] [INFO] Listening at: http://127.0.0.1:8000 (15)
taiga-back | [2020-05-03 02:50:13 +0000] [15] [INFO] Using worker: sync
taiga-back | [2020-05-03 02:50:13 +0000] [30] [INFO] Booting worker with pid: 30
taiga-back | Error: 
taiga-back | Unable to load celery application.
taiga-back | The module settings.celery was not found.
taiga-back | 
taiga-back | [2020-05-03 02:50:13 +0000] [31] [INFO] Booting worker with pid: 31
taiga-back | [2020-05-03 02:50:13 +0000] [32] [INFO] Booting worker with pid: 32
taiga-back | [2020-05-03 02:50:13 +0000] [30] [ERROR] Exception in worker process
taiga-back | Traceback (most recent call last):
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 28, in <module>
taiga-back |     from settings import celery_local as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
taiga-back |     worker.init_process()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
taiga-back |     self.load_wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
taiga-back |     self.wsgi = self.app.wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
taiga-back |     self.callable = self.load()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
taiga-back |     return self.load_wsgiapp()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
taiga-back |     return util.import_app(self.app_uri)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
taiga-back |     __import__(module)
taiga-back |   File "/srv/taiga/back/taiga/__init__.py", line 19, in <module>
taiga-back |     from . import celery
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 30, in <module>
taiga-back |     from settings import celery as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | [2020-05-03 02:50:13 +0000] [30] [INFO] Worker exiting (pid: 30)
taiga-back | [2020-05-03 02:50:13 +0000] [31] [ERROR] Exception in worker process
taiga-back | Traceback (most recent call last):
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 28, in <module>
taiga-back |     from settings import celery_local as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
taiga-back |     worker.init_process()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
taiga-back |     self.load_wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
taiga-back |     self.wsgi = self.app.wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
taiga-back |     self.callable = self.load()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
taiga-back |     return self.load_wsgiapp()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
taiga-back |     return util.import_app(self.app_uri)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
taiga-back |     __import__(module)
taiga-back |   File "/srv/taiga/back/taiga/__init__.py", line 19, in <module>
taiga-back |     from . import celery
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 30, in <module>
taiga-back |     from settings import celery as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | [2020-05-03 02:50:13 +0000] [31] [INFO] Worker exiting (pid: 31)
taiga-back | [2020-05-03 02:50:13 +0000] [32] [ERROR] Exception in worker process
taiga-back | Traceback (most recent call last):
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 28, in <module>
taiga-back |     from settings import celery_local as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
taiga-back |     worker.init_process()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
taiga-back |     self.load_wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
taiga-back |     self.wsgi = self.app.wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
taiga-back |     self.callable = self.load()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
taiga-back |     return self.load_wsgiapp()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
taiga-back |     return util.import_app(self.app_uri)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
taiga-back |     __import__(module)
taiga-back |   File "/srv/taiga/back/taiga/__init__.py", line 19, in <module>
taiga-back |     from . import celery
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 30, in <module>
taiga-back |     from settings import celery as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | [2020-05-03 02:50:13 +0000] [32] [INFO] Worker exiting (pid: 32)
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 203, in run
taiga-back |     self.manage_workers()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
taiga-back |     self.spawn_workers()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
taiga-back |     time.sleep(0.1 * random.random())
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
taiga-back |     self.reap_workers()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
taiga-back |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
taiga-back | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/bin/gunicorn", line 10, in <module>
taiga-back |     sys.exit(run())
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
taiga-back |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
taiga-back |     super(Application, self).run()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
taiga-back |     Arbiter(self).run()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 232, in run
taiga-back |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 345, in halt
taiga-back |     self.stop()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
taiga-back |     time.sleep(0.1)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
taiga-back |     self.reap_workers()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
taiga-back |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
taiga-back | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

```

**Comment by catpreneur** [comment]
This happened when i updated the main taiga docker repository. Before it was 5.0.8 i think.

**Comment by catpreneur** [comment]
If i run it from an empty directory, it starts up fine. But if i'm using it with data from an older version, it doesn't load/login/etc. I notice the Upgrading section is still marked as todo.

**Comment by catpreneur** [comment]
Nvm figured it out. The new version uses celery w/ redis and the conf/back/celery.py file was missing in the old installation. Just copied the one from the fresh installation to the old and it works. May want to document this.
