### ISSUE TITLE
Imposible to export project

### ISSUE THREAD

**Issue by sauljabin** [docker-taiga/back#2]
We have problems exporting projects:
ValueError: invalid literal for int() with base 10: '<email>'

```
ERROR:2018-11-08 16:40:03,446: Internal Server Error: /api/v1/exporter/16
Traceback (most recent call last):
  File "/srv/taiga/back/taiga/export_import/serializers/cache.py", line 35, in cached_get_user_by_pk
    _cache_user_by_pk[pk] = users_models.User.objects.get(pk=pk)
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1261, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1221, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1115, in build_lookup
    return final_lookup(lhs, rhs)
  File "/usr/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'an_email@here.com'
```

Using the most recent version dockertaiga/back

**Comment by sauljabin** [comment]
Hi, maybe it is necessary upgrade the container version to 3.4.5 (2018-10-15)?

**Comment by w1ck3dg0ph3r** [comment]
Hi, I'm unable to reproduce this - the project exported just fine here. Seems to be taiga's or specific project's issue to me.

**Comment by sauljabin** [comment]
Hi, you're right, I was able to export projects, I already know what the scenario was, a project from an older version of taiga was imported, then I tried to export and gave that error, but it happens in that project, not in the new ones.

Thank you very much for your answer.
