### ISSUE TITLE
Enable async tasks

### ISSUE THREAD

**Issue by VisualFox** [docker-taiga/back#9]
with commit 06125618f16a9f831c27f82a7666f179983297d5
I am getting this error:

    Traceback (most recent call last):
    File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
    File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
    File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
    File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
    File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
    File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
    from .celery import *
    ModuleNotFoundError: No module named 'settings.celery'
    Traceback (most recent call last):
    File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
    File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
    File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
    File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
    File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
    File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
    from .celery import *

I am way to unfamiliar to django and celery to know how to fix that. I can only guess that linked to this:

    ModuleNotFoundError: No module named 'settings.celery'

**Comment by w1ck3dg0ph3r** [comment]
My guess is, with preexisting volumes you should put `celery.py` alongside `config py` inside `/taiga-conf` volume (and use the fix in 251d53e as well).

**Comment by VisualFox** [comment]
Ah that makes sense. I am going to try that and I will report back. Thank you for your work!

**Comment by VisualFox** [comment]
That worked thanks! 

Just a side note I was not actually using redis/rabbit as I didn't need the functionality. In config.py:

    EVENTS_PUSH_BACKEND = ""
    EVENTS_PUSH_BACKEND_OPTIONS = ""

    CELERY_ENABLED = False

but taiga continue to try to connect to rabbit

    [2020-02-11 11:55:33,567: ERROR/MainProcess] consumer: Cannot connect to amqp://taiga:**@rabbit:5672/taiga: failed to resolve broker hostname.

**Comment by VisualFox** [comment]
I am closing this issue as putting celery.py inside the existing volume solved my issue. Thank you!
